authors:
 montimaj:
    name: Sayantan Majumdar
    description: Assistant Research Professor, Hydrologic Sciences and Remote Sensing, Desert Research Institute
    avatar: https://github.com/montimaj.png
